layers:
  - type: Conv2d
    params:
      in_channels: 1
      out_channels: 128
      kernel_size: 7
      stride: 2
      padding: 3
      bias: false

  - type: BatchNorm2d
    params:
      num_features: 128

  - type: ReLU
    params:
      inplace: true

  - type: MaxPool2d
    params:
      kernel_size: 3
      stride: 2
      padding: 1

  - type: ResidualLayer
    params:
      out_channels: 128
      blocks: 2
      stride: 2

  - type: ResidualLayer
    params:
      out_channels: 256
      blocks: 2
      stride: 2

  - type: ResidualLayer
    params:
      out_channels: 512
      blocks: 2
      stride: 2

  - type: ResidualLayer
    params:
      out_channels: 1024
      blocks: 2
      stride: 2

  - type: AdaptiveAvgPool2d
    params:
      output_size: [1, 1]

  - type: Flatten
    params:

  - type: Linear
    params:
      in_features: 1024
      out_features: 512

  - type: ReLU
    params:
      inplace: true

  - type: Linear
    params:
      in_features: 512
      out_features: 10