defaults:
  - _self_
  - architecture: original_architecture

save_parameters:
  model_path: ./models
  model_name: Original_TestNumberModelForTFLite
  save_model: true
  load_model: null
  trace_sample: true
training:
  dataset_path: ./cell_dataset
  train_test_split: 0.8
  epochs: 80
  lrate: 0.001
  lrate_scheduler:
    enable: true
    type: cosine_annealing
    parameters:
      T_max: 80
  batch_size: 50
hardware:
  device: cuda
misc:
  verbose_architecture: false
  display_loss: false
