defaults:
  - _self_
  - architecture: original_architecture

save_parameters:
  model_path: ./models
  model_name: Original_TestNumberModelForTFLite
  save_model: true
  load_model: null
  trace_sample: true
training:
  epochs: 80
  lrate: 0.001
  batch_size: 50
hardware:
  device: cuda
misc:
  verbose_architecture: false
  display_loss: false
